### ISSUE TITLE
Use Python "connexion" library for Swagger-first REST server with OAuth support

### ISSUE THREAD

**Issue by hjacobs** [zalando/saiki-lawang#1]
https://github.com/zalando/connexion

I can create a first draft/example if you want.. :-)

**Comment by drummerwolli** [comment]
highly appreciated ... this is basically API documentation and oauth implementation for any REST API, right? you still need to program an API first ...

**Comment by drummerwolli** [comment]
we changed to a java based version, this repo will be merged into another soonish anyway. will close this for now ...
